Handle base errors

diff --git a/commands/base b/commands/base
--- a/commands/base
+++ b/commands/base
@@ -1,18 +1,52 @@
 #!/bin/bash
 
 APP_USER_LINUX=#{APP_USER_LINUX}
-
+bold=$(tput bold)
+normal=$(tput sgr0)
 
 sudo su - $APP_USER_LINUX << \EOF
     CONF_ROOT=/var/local
     source $CONF_ROOT/config.txt
-    echo -e "Clonig git repository from this url:  $GIT_REPO_URL"
-    cd /home/$APP_USER
-    git clone $GIT_REPO_URL
+    source $CONF_ROOT/status.txt
+
+    if [ $REPO_CLONE ]; then
+        echo "Repository check ...."
+        sleep 3
+        echo "\e[32mAlready have $GIT_REPO_URL ............... [OK]\e[0m"
+    else
+        echo -e "Clonig git repository from this url:  $GIT_REPO_URL"
+        cd /home/$APP_USER
+        git clone $GIT_REPO_URL
+        echo "REPO_CLONE=True" >> $CONF_ROOT/status.txt
+    fi
     cd $GIT_ROOT
-    APP_ROOT_DIRECTOR=$(pwd)
-    echo "APP_ROOT_DIRECTOR=$APP_ROOT_DIRECTOR" >> "$CONF_ROOT/config.txt"
+    if [ $ROOT_DIRECTOR ]; then
+        echo "Check project root directory"
+    else
+        APP_ROOT_DIRECTOR=$(pwd)
+        echo "APP_ROOT_DIRECTOR=$APP_ROOT_DIRECTOR" >> "$CONF_ROOT/config.txt"
+        echo "ROOT_DIRECTOR=True" >> $CONF_ROOT/status.txt
+    fi
     cd $APP_ROOT_DIRECTOR
+    if [ ! -f "manage.py" ]; then
+        echo -e "\e[31mERROR $(date): manage.py file doest exist the system"
+        echo -e "Please make sure your django application modern root directory look like:"
+        echo -e "|-- base_app_name"
+        echo -e "|   |-- __init__.py"
+        echo -e "|   |-- settings.py"
+        echo -e "|   |-- urls.py"
+        echo -e "|   `-- wsgi.py"
+        echo -e "|-- app_name"
+        echo -e "|   |-- admin.py"
+        echo -e "|   |-- apps.py"
+        echo -e "|   |-- __init__.py"
+        echo -e "|   |-- models.py"
+        echo -e "|   |-- views.py"
+        echo -e "|   `-- tests.py"
+        echo -e "|-- ${bold}manage.py${normal}"
+        echo -e "|-- ${bold}requirements.txt${normal}"
+        exit 123
+    fi
     echo -e "Create Virtualenviroment"
     python3 -m venv .venv
     echo -e "Activate virtualenviroment"
